#配置数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: root




#设置mp相关的配置
mybatis-plus:
   global-config:
     db-config:
       table-prefix: tb1_
